// Generated by CoffeeScript 1.10.0
(function() {
  var _, dictionary, fs, getBeers, isASCII, mbit;

  mbit = (require('microbrewit-node')).init();

  _ = require('lodash');

  fs = require('fs');

  isASCII = function(str) {
    return /^[\x00-\x7F]*$/.test(str);
  };

  dictionary = [];

  getBeers = function(skip) {
    if (skip == null) {
      skip = 0;
    }
    return mbit.beers.get({
      size: 1000,
      from: skip
    }, function(err, res, body) {
      var beer, beerName, dict, i, len, ref;
      ref = body.beers;
      for (i = 0, len = ref.length; i < len; i++) {
        beer = ref[i];
        beerName = beer.name.toLowerCase().replace(/[^a-z]/gmi, " ").replace(/\s+/g, " ");
        if (isASCII(beerName)) {
          dict = beerName.split(' ');
          if (dict.length > 1) {
            dictionary = dictionary.concat(dict);
          } else {
            dictionary.push(beerName);
          }
        }
      }
      if (skip < 250000) {
        console.log("Iteration " + (skip / 1000));
        return getBeers(skip + 1000);
      } else {
        dictionary = _.uniq(dictionary);
        return fs.writeFileSync('./dictionary.json', JSON.stringify(dictionary));
      }
    });
  };

  getBeers();

}).call(this);
