// Generated by CoffeeScript 1.10.0
(function() {
  var Foswig, chain, e, error, fs;

  Foswig = require('foswig');

  fs = require('fs');

  chain = new Foswig(4);

  try {
    chain.addWordsToChain(JSON.parse(fs.readFileSync('./dictionary.json')));
  } catch (error) {
    e = error;
    console.error('Could not read dictionary.');
  }

  exports.generateMarkov = function(min, max, unique, words) {
    var i, j, name, ref;
    if (min == null) {
      min = 5;
    }
    if (max == null) {
      max = 10;
    }
    if (unique == null) {
      unique = false;
    }
    if (words == null) {
      words = 1;
    }
    name = [];
    for (i = j = 0, ref = words; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      name.push(chain.generateWord(min, max, false));
    }
    return name.join(' ');
  };

  exports.randomMarkov = function(min, max) {
    var words;
    if (min == null) {
      min = 1;
    }
    if (max == null) {
      max = 3;
    }
    words = Math.floor(Math.random() * (max - min + 1)) + min;
    return this.generateMarkov(3, 10, true, words);
  };

}).call(this);
