// Generated by CoffeeScript 1.10.0
(function() {
  var generator, server;

  server = new (require('hapi')).Server();

  generator = require('./markov');

  server.connection({
    port: 4000,
    host: 'localhost'
  });

  server.route([
    {
      method: 'GET',
      path: '/',
      handler: function(req, reply) {
        if (req.query.callback != null) {
          return reply(req.query.callback + "({\"name\":\"" + (generator.randomMarkov(1, 3)) + "\"})");
        } else {
          return reply(generator.randomMarkov(1, 3));
        }
      }
    }
  ]);

  server.start(function() {
    return console.log("Running!");
  });

}).call(this);
